# <font color="steelblue">Módulo Pandas: Manipulación y combinación de conjuntos de datos</font>

**Material desarrollado por los [equipos de trabajo de IA4LEGOS](https://ia4legos.umh.es/)**


**Fecha última edición**: 10/05/2025

**Licencia**: <small><a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /></small>

No olvides hacer una copia si deseas utilizarlo. Al usar estos contenidos, aceptas nuestros términos de uso y nuestra política de privacidad.

## <font color="steelblue">Configuración del cuaderno</font>

Para garantizar la funcionalidad completa de este cuaderno, es preciso ejecutar la celda de código a continuación.

In [ ]:
#@title <font color="steelblue" size="+1"> Descarga de ficheros a colab y funciones para colorear tablas{ display-mode: "form" }
# Lectura de los csv
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/marvel_caracteristicas.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/dc_caracteristicas.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/marvel_sexo.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/dc_sexo.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/nutricion1.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/nutricion2.csv"}
!wget {f"https://raw.githubusercontent.com/ia4legos/Statistics/main/data/provincias.csv"}
# Definimos funciones
def highlight(df):
      if df["Cómic"] == "MARVEL":
          return ['background-color: magenta'] * len(df)
      elif df["Cómic"] == "DC":
          return ['background-color: pink'] * len(df)
      else:
          return ['background-color: pink'] * len(df)

def highlight2(df):
      if df["comic"] == "DC":
          return ['background-color: pink'] * len(df)
      else:
          return ['background-color: white'] * len(df)

def highlight3(df):
      if df["Sexo"] in ["HOMBRE", "MUJER"]:
          return ['color:white; background-color:darkblue'] * len(df)
      else:
          return ['background-color: white'] * len(df)

def highlight4(df):
          if df["Sexo"] in ["HOMBRE", "MUJER"]:
              return ['background-color: lightblue'] * len(df)
          else:
              return ['background-color: white'] * len(df)

def highlight5(df):
          if df["Nombre superhéroe"] in ["Batman", "Harley Quinn"]:
              return ['background-color: lightblue'] * len(df)
          else:
              return ['color:white; background-color:darkblue'] * len(df)

def highlight6(df):
      if df["Cómic"] == "MARVEL":
          return ['background-color: magenta'] * len(df)
      else:
          return ['color:white; background-color:darkblue'] * len(df)

def highlight7(df):
      if df[4] == "MARVEL":
          return ['background-color: magenta'] * (len(df)-2) + ['color:white; background-color:darkblue'] * 2
      else:
          return ['background-color: white'] * len(df)

def highlight8(df):
      if df[4] == "DC":
          return ['background-color: pink'] * (len(df)-2) + ['background-color: lightblue'] * 2
      else:
          return ['background-color: white'] * len(df)

def highlight9(df):
          if df["Nombre superhéroe"] in ["Batman", "Linterna Verde", "Wonder Woman"]:
              return ['background-color: pink'] * len(df)
          else:
              return ['background-color: magenta'] * len(df)

def highlight10(df):
      if df["Cómic"] in ["MARVEL", "DC"]:
          return ['background-color: magenta'] * len(df)
      else:
          return ['background-color: white'] * len(df)

def highlight11(df):
      if df["_merge"] == "left_only":
          return ['background-color: magenta'] * len(df)
      elif df["_merge"] == "right_only":
          return ['color:white; background-color:darkblue'] * len(df)
      else:
          return ['color:white; background-color: darkviolet'] * len(df)

def highlight12(df):
          if df["Sexo"] in ["HOMBRE", "MUJER"]:
              return ['color:white; background-color: darkviolet'] * len(df)
          else:
              return ['background-color: magenta'] * len(df)

Cuaderno configurado

## <font color='steelblue'>Introducción</font>

**Descripción:** Es frecuente, en la práctica estadística, encontrar información relevante sobre el tema que nos interesa en distintas fuentes, y por lo tanto descargable en ficheros también distintos. Es pues necesario, saber cómo combinar información de varios ficheros o bases de datos para tener toda la información compendiada en una única base de datos con la que llevar a cabo el análisis. Estudiamos en este cuaderno la combinación de bases de datos, tanto a nivel de añadir más registros, como de añadir más columnas o variables de interés.

Como excusa para ejemplificar las propuestas, investigamos si los superhéroes en los cómics de Marvel y DC tienen condiciones físicas extraordinarias.

## <font color='steelblue'> Objetivos de aprendizaje

* Reflexionar sobre la necesidad de la combinación de bases de datos.

* Conocer y aplicar los modos de integrar nuevos datos en una base de datos dadas, utilizando dataframes y la librería *Pandas*.

* Reconocer variables relacionales en bases de datos distintas susceptibles de compartir información para ampliarla.

* Conocer y aplicar los modos de integrar nuevas variables en una base de datos dadas, utilizando dataframes y la librería *Pandas*.

* Integrar varias bases de datos para investigar a un nivel básico sobre la hipermasculinidad y la hiperfeminidad de los/las superhéroes/heroínas de los cómics.

* Aplicar diversas funciones de agrupación y descripción estudiadas en cuadernos previos, para resolver la pregunta sobre los cómics y comparar superhéroes con la población normal.

* Interpretar y analizar los resultados obtenidos en relación con las preguntas de investigación planteadas.

## <font color='steelblue'> Contenidos </font>

1. ¿Para qué combinamos bases de datos?
1. Combinar añadiendo filas
1. Combinar añadiendo columnas

## <font color='steelblue'> 1. ¿Para qué combinamos bases de datos?

A veces es necesario ampliar el conjunto de datos inicial con información adicional de un segundo conjunto de datos (o incluso de otros adicionales). Para ello, se pueden leer los dos conjuntos de datos y luego combinarlos en uno solo para tener información completa con la que llevar a cabo nuestro análisis. Sin embargo, dependiendo de cómo se combinen las bases de datos, podemos terminar con más o menos datos de los esperados, por lo que siempre hemos de asegurarnos de no perder involuntariamente datos que son valiosos para el análisis.

Unir y combinar (*merge* en inglés) varias bases de datos es un proceso obvio cuando sabemos unir y combinar simplemente dos bases de datos. Estos procesos los llevaremos a cabo con las funciones **`concat()`** o **`merge()`** del módulo _Pandas_.


Podemos encontrar bases de datos dispares que nos interesa combinar, pero en cualquier caso, entre ellas ha de existir siempre algún nexo de unión, esto es, alguna variable que compartan y respecto de la cual podamos vincular los datos que contienen. Lo habitual es considerar una de esas bases de datos, la más completa para nuestro análisis, y completarla con la información adicional que aporta la otra. Con todo, siempre es posible crear una base de datos diferente a las disponibles, que contenga solo la información relevante de cada una.

Vamos a plantear dos casos habituales a la hora de combinar dos bases de datos:

- Las bases de datos tienen las mismas variables, y las combinamos para completar los registros disponibles en unas y otras.
- Las diferentes bases de datos tienen al menos una variable en común, y las combinamos para añadir variables respecto de la base de datos más completa.

Mostraremos cómo resolver estos casos, pero primero de todo importamos las librerías necesarias: *NumPy* y *Pandas*:

In [ ]:
import numpy as np
import pandas as pd

Vamos a trabajar con diversos ficheros que contienen características de los superhéroes de Marvel y DC. Se trata de los ficheros:
-  *marvel_caracteristicas.csv*,
- *dc_caracteristicas.csv*,
- *marvel_sexo.csv*,
- *dc_sexo.csv*.

Los dos primeros (los terminados en *'_caracteristicas'*) tienen 5 variables:
- Nombre del superhéroe
- Su nombre humano
- Peso
- Talla
- Compañía de cómics a la que pertenece (MARVEL o DC)

Los otros dos (los terminados en *'_sexo'*) tienen tan solo 2 variables:
- Nombre del superhéroe
- Sexo (HOMBRE o MUJER)

Vamos a trabajar con estas bases de datos debido al estudio *Burch, R. L., & Johnsen, L. (2019)*, titulado [Captain Dorito and the Bombshell: Supernormal Stimuli in Comics and Film](https://psycnet.apa.org/record/2019-21845-001), publicado en la revista científica *Evolutionary Behavioral Sciences*. En este artículo se habla sobre la hipermasculinidad en las dimensiones físicas de los superhéroes hombres y la hiperfeminidad en las mujeres superhéroes. Para comprobar estas afirmaciones nos hemos propuesto calcular los IMC (Índice de Masa Corporal) de cada uno de ellos, calcular su media por sexo y comparar esas medias con las medias correspondientes de los jóvenes en Estados Unidos.

Pero para ello necesitamos importar, visualizar y combinar toda la información disponible en una única base de datos.
Para visualizar mejor las diferentes bases de datos, se han generado unas funciones (propias) para colorearlas en pantalla y así mostrar rápidamente de qué base proviene cada dato. Para ello conseguir esta coloración diferenciada utilizamos la función `apply` para aplicar las funciones a cada _dataframe_.

Empezamos inspeccionando las bases de datos de Marvel.

In [ ]:
df1 = pd.read_csv("marvel_caracteristicas.csv", sep=";")
df1.style.apply(highlight, axis=1)

Tenemos tan solo 6 registros de superhéroes de Marvel. El no tener el nombre humano de Nébula (reconocido como _nan_), no supone problema alguno, pues para nuestros fines interesarán fundamentalmente las variables `peso` y `talla`.

A continuación, leemos la información sobre los superhéroes de DC, con tres registros.

In [ ]:
df2 = pd.read_csv("dc_caracteristicas.csv", sep=";")
df2.style.apply(highlight2, axis=1)

Leemos ahora el fichero con la información sobre el sexo de los superhéroes de Marvel, con 7 registros, algunos de los cuales no coinciden con el fichero Marvel con todas las características.

In [ ]:
df3 = pd.read_csv("marvel_sexo.csv", sep=";")
df3.style.apply(highlight3, axis=1)

Y hacemos lo propio con los superhéroes de DC, con dos registros y que no coinciden exactamente con los superhéroes en el fichero DC de características.

In [ ]:
df4 = pd.read_csv("dc_sexo.csv", sep=";")
df4.style.apply(highlight4, axis=1)

Al inspeccionar estas bases de datos, observamos que en ninguna de ellas existen **registros duplicados**. En caso de existir, antes de combinar dataframes habríamos de proceder excluyendo los registros duplicados en cada una de las bases de datos a combinar.

Esto lo conseguimos con la función **`drop_duplicates()`** de _Pandas_ y su sintaxis será: `data_frame.drop_duplicates()`. Por defecto para encontrar los duplicados utiliza todas las columnas a la vez, pero podemos especificar cuál es la columna o columnas cuyo valor repetido ha de interpretar como duplicado. También permite especificar con cuál de las repeticiones ha de quedarse; con el argumento `keep='first'` mantendrá el registro de la primera aparición de dicho valor, y con `keep='last'` el último.

Está claro ahora que necesitaremos combinar toda la información. Si bien hay diversos modos de abordar esta combinación de datos, buscaremos:
1. juntar toda la información proveniente de Marvel y DC sobre las características de los superhéroes,
1. juntar toda la información proveniente de Marvel y DC sobre el sexo de los superhéroes
1. reunir la información completa de Marvel y DC.

Las acciones 1 y 2 las gestionaremos **anexando/concatenando** todos los registros de Marvel y de DC sobre las *características* de los superhéroes por un lado, y sobre su *sexo* por otro. La acción 3 la abordaremos **combinando** la base de datos de *características* con la de *sexo*, aprovechando el hecho de que ambas comparten una variable común que las relaciona, y que es `Nombre superhéroe`, y completando con toda la información disponible en los dos dataframes sobre los superhéroes.

## <font color='steelblue'> 2. Combinar añadiendo filas

Observamos pues, al visualizar las bases de datos respectivas correspondientes a *caracteristicas* (y también las de *sexo*), que ambos dataframes **comparten todas las variables**.

La opción entonces para combinar los ficheros de *características* entre sí (y los de *sexo* entre sí), es **concatenarlas**, esto es, colocarlas una a continuación de la otra en filas consecutivas, con la función **`concat()`** del módulo _Pandas_.

Para ello pasamos dentro de una lista los dataframes de *caracteristicas* como argumentos de la función. Se crea un nuevo objeto que concatena por filas los dataframes introducidos:
```
df_caracteristicas = pd.concat([df1, df2])
```

Si utilizamos la función `concat(...,axis=1)` con el argumento `axis=1`, la unión o concatenación de bases de datos se realiza por columnas, y no por filas como en la opción por defecto `axis=0`.

In [ ]:
# Anexado de registros con sus columnas/variables originales
df_caracteristicas = pd.concat([df1, df2])
df_caracteristicas

  Nombre superhéroe     Nombre humano  Peso Talla   Cómic comic
0          Tormenta      Ororo Munroe    66  1,81  MARVEL   NaN
1   Capitán América      Steve Rogers   109  1,88  MARVEL   NaN
2              Hulk      Bruce Banner   635     3  MARVEL   NaN
3       Viuda Negra  Natasha Romanoff    59   1,7  MARVEL   NaN
4            Nébula               NaN    82  1,85  MARVEL   NaN
5           Lobezno     James Howlett   136   1,6  MARVEL   NaN
0    Linterna Verde     Harold Jordan    91  1,82     NaN    DC
1      Wonder Woman      Diana Prince    75  1,83     NaN    DC
2            Batman       Bruce Wayne    95  1,85     NaN    DC

 Nos percatamos entonces lo que ya debimos percartarnos inicialmente: la última columna/variable en los dataframe de *caracteristicas* tiene una grafía diferente en Marvel (`Cómic`) y DC (`comic`). Esto da lugar a la creación de dos columnas diferentes rellenadas con valores faltantes `NaN` cuando no contienen información.

 Para solucionar este problema, hemos de conseguir que todas las variables, en todos los dataframe que unimos, tengan la misma grafía. Esto lo conseguimos con la función `rename()`, con la  que cambiamos el nombre de la variable en conflicto en alguno de los dataframes a unir.

 También observamos que los índices en el dataframe concatenado, provienen de los índices de los dataframes originales, con lo cual aparecen repetidos. Si los índices originales no tienen información específica, como es el caso porque son meros numerales, deberíamos crear un índice único que numere las filas del dataframe completo. Esto lo conseguimos con el argumento `ignore_index=True` en la función `concat()`.

Procedemos y al realizar bien la unión, ya podemos aplicar nuestra función `highlight` que diferencia por colores los datos de uno y otro dataframe.

In [ ]:
# Anexado de registros asegurando nombres de columnas iguales

# Se renombra una de las columnas diferentes
df2_r = df2.rename(columns={'comic':'Cómic'})
# Se anexan las características de los superhéroes de Marvel y de DC
df_caracteristicas = pd.concat([df1, df2_r], ignore_index = True)
df_caracteristicas.style.apply(highlight, axis=1)

Otra opción alternativa es construir un nuevo dataframe que contenga solo la información de las variables compartidas. Esto lo conseguimos incorporando el argumento **`join='inner'`** en la función `concat()`. Si las variables que no comparten, no son relevantes para nuestro análisis, es una opción interesante, pues genera un dataframe más simple.

El valor por defecto en el argumento `join` es `'outer'`, que da el resultado que vimos al principio cuando conseguíamos un nuevo dataframe con una columna llamada `Cómic`(del dataframe `df1`), y otra llamada `comic` (del dataframe `df2`).


Si aplicamos entonces el argumento `join='inner'` para unir los registros de características de Marvel y DC, se mantienen las columnas `Nombre superhéroe`, `Nombre humano`, `Peso` y `Talla`, PERO perdemos la última columna en los dos dataframes, al tener nombres (realmente grafías) distintos. En nuestro caso NO nos interesa perder esta información, por lo que no será la opción que usemos para el análisis. No obstante veamos cuál sería el resultado.

In [ ]:
# Anexado de registros solo con columnas en común
df_prueba = pd.concat([df1, df2], join = 'inner', ignore_index = True)
df_prueba.style.apply(highlight9, axis=1)

Otra forma sencilla de unir dos dataframes es mediante la función **`append()`**, que ya utilizamos para añadir valores a las listas. Para ello se usa uno de los dataframes como referente, al que se le añadirán los registros ubicados en los dataframes incluidos en los argumentos de la función. Obviamente, para que el añadido de registros funcione adecuadamente, hemos de asegurarnos de que coinciden los nombres de todas las columnas en los dataframes que combinamos. Para mantener el resultado con todos los registros unidos, hemos de asignarlo a un nuevo objeto.

Esta opción con `append()` sin embargo, no nos permite modificar los índices originales en los dataframes, por lo que es inviable utilizar nuestra función de coloreado de datos para diferenciar Marvel y DC.

Veamos cómo funciona.

In [ ]:
# Anexado de registros asegurando nombres de columnas iguales
df1.append(df2_r)

<ipython-input-17-4f44ae17cc66>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2_r)

  Nombre superhéroe     Nombre humano  Peso Talla   Cómic
0          Tormenta      Ororo Munroe    66  1,81  MARVEL
1   Capitán América      Steve Rogers   109  1,88  MARVEL
2              Hulk      Bruce Banner   635     3  MARVEL
3       Viuda Negra  Natasha Romanoff    59   1,7  MARVEL
4            Nébula               NaN    82  1,85  MARVEL
5           Lobezno     James Howlett   136   1,6  MARVEL
0    Linterna Verde     Harold Jordan    91  1,82      DC
1      Wonder Woman      Diana Prince    75  1,83      DC
2            Batman       Bruce Wayne    95  1,85      DC

Hacemos lo mismo ahora con los dataframes que almacenan el sexo de cada superhéroe. En este caso solo tenemos que ignorar los índices originales, pues los nombres de las columnas coinciden en ambas.

In [ ]:
# Anexado de registros asegurando nombres de columnas iguales
df_sexo = pd.concat([df3, df4], ignore_index = True)
df_sexo.style.apply(highlight5, axis=1)

El siguiente objetivo es combinar los datos completos (de Marvel y DC) disponibles sobre características de los superhéroes (en el dataframe `df_caracteristicas`), con la información sobre el sexo (en el dataframe `df_sexo`).

Probemos a utilizar la función `concat()`, pero ahora uniendo por columnas, con el argumento `axis=1`.

In [ ]:
# Anexado (concat) de dos bases de datos por columnas
pd.concat([df_caracteristicas, df_sexo], axis=1)

,Nombre superhéroe,Nombre humano,Peso,Talla,Cómic,Nombre superhéroe,Sexo
0,Tormenta,Ororo Munroe,66,"1,81",MARVEL,Capitana Marvel,MUJER
1,Capitán América,Steve Rogers,109,"1,88",MARVEL,Iron Man,HOMBRE
2,Hulk,Bruce Banner,635,3,MARVEL,Hulk,HOMBRE
3,Viuda Negra,Natasha Romanoff,59,"1,7",MARVEL,Viuda Negra,MUJER
4,Nébula,NaN,82,"1,85",MARVEL,Nébula,MUJER
5,Lobezno,James Howlett,136,"1,6",MARVEL,Lobezno,HOMBRE
6,Linterna Verde,Harold Jordan,91,"1,82",DC,Batman,HOMBRE
7,Wonder Woman,Diana Prince,75,"1,83",DC,Harley Quinn,MUJER
8,Batman,Bruce Wayne,95,"1,85",DC,NaN,NaN

El resultado es que ha pegado las variables/columnas en los dos dataframes, de modo que:
1. se repite la variable `Nombre superhéroe`;
1. completa bien la información para aquellos superhéroes que están en los dos dataframes (Hulk, Viuda Negra, Nébula y Lobezno)
1. completa mal la información para aquellos superhéroes que solo están en alguno de los dos dataframes (Tormenta, Capitán América, Capitana Marvel, Iron Man, Linterna Verde, Batman, Wonder Woman, Harley Quinn y Batman).
1. Rellena con `NaN` cuando la dimensión de las coincidencias o no coincidencias no es la misma en los dataframes combinados.

No conseguimos pues, la combinación de información deseada, por lo que habremos de buscar otras opciones que resolvemos en la siguiente sección.

## <font color='steelblue'> 3. Combinar añadiendo columnas

El otro caso que mencionamos al inicio, y que se plantea al final de la sección anterior, es el de combinar dos o más bases  de datos que tienen una o más variables en común. Estas bases de datos se llaman **relacionales**.

Esta situación de bases de datos relacionales ocurren con frecuencia en la práctica. Por ejemplo cuando el proveedor de datos una empresa almacena información en diferentes tablas: una para los datos de las ventas, otra para los datos sobre los productos en stock, otra con los datos de los clientes, etc., pero mantiene siempre alguna variable de relación entre ellas para poderlas relacionar en un momento dado si necesita combinar la información. Esta variable relacional podría ser, por ejemplo, un identificador de los productos, para en un momento dado mostrar ventas y existencias, o el identificador de los clientes, para generar informes de las compras que realizan, cuándo y de qué productos.


A este proceso de unir bases de datos para combinar la información que contienen respecto de las variables comunes, y añadir otras variables no comunes en otras bases de datos, nos vamos a referir por el nombre de **combinar** información. Para hacerlo en Python utilizamos la función `merge()` del módulo _Pandas_.


Comenzamos con el dataframe de características, `df_caracteristicas`, que almacena todas las características de los superhéroes (ya sean de Marvel o DC) y seguiremos con `df_sexo`, que da la información sobre el sexo de cada superhéroe (hombre o mujer). Los recordamos a continuación, coloreados para que más tarde a la hora de unirlos podamos ver dónde se genera la unión.

In [ ]:
# Características de los superhéroes (Marvel y DC)
df_caracteristicas.style.apply(highlight10, axis=1)

In [ ]:
# Sexo de los superhéroes (Marvel y DC)
df_sexo.style.apply(highlight3, axis=1)

A estas alturas ya tenemos claro que queremos combinar las dos bases de datos, que comparten como variable relacional la columna `Nombre superhéroe`, que recibe el nombre de columna clave (*key*). Al combinar dataframes, siempre se escribirán en orden, por lo que podremos referirnos al de la izquierda (el primero en ser escrito) y al de la derecha (el segundo). La sintaxis que utilizamos para combinarlas puede ser cualquiera de las siguientes expresiones:
```
df_nuevo = pd.merge(df_izquierda, df_derecha)
df_nuevo = df_izquierda.merge(df_derecha)
```

Nos centramos a continuación en los siguientes argumentos de la función: `how`, `on`, `on_left`, `on_right` e `indicator`. Si quieres investigar más sobre la función `merge()` puedes consultar el [Tutorial de Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html).

Aunque la función `merge()` es bastante eficiente para encontrar la columna clave en los _dataframes_ a fusionar, nunca está de más especificarlo en el argumento **`on`**. Además, esto acelera el tiempo de ejecución.


Como la columna clave tiene el mismo nombre en los dos dataframes a combinar, el código para nuestro ejemplo quedaría:
```
df_nuevo = df_caracteristicas.merge(df_sexo, on='Nombre superhéroe')
```

En el caso en que la columna clave tuviera distintos nombres en los dataframes a combinar, tenemos dos opciones:
1. cambiar el nombre de la columna clave en uno de ellos para igualarlo al del otro
1. especificar los nombres de las columnas en cada uno de los dataframes a combinar, con los argumentos **`on_left`** (nombre en el dataframe de la izquierda) y **`on_right`** (nombre en el dataframe de la derecha):
```
df_nuevo = df_caracteristicas.merge(df_sexo,
                      on_left='Nombre superhéroe',
                      on_right='nombre_superheroe')
```

El argumento booleano **`indicator`** toma por defecto el valor `False`. Si lo hacemos `True`, añade una columna llamada `merge` al dataframe resultado, con la información sobre la fuente de cada fila o registro. Esta variable nos ayudará a comprobar que la fusión se ha realizado correctamente, o simplemente a identificar de dónde proviene cada registro.

Por último nos queda por hablar del argumento **`how`**, que nos permite combinar de distintos modos los dataframes de interés. Veamos las posibilidades más populares y cómo funcionan:

- `how='outer'`: aparecen TODAS las claves de ambas bases de datos:

  <center><img src=https://raw.githubusercontent.com/ia4legos/Statistics/main/images/img_180_30_10.JPEG width="1000" height="150"></center>

- `how=inner`: aparecerán solo las claves que coinciden en ambas bases de datos.

  <center><img src=https://raw.githubusercontent.com/ia4legos/Statistics/main/images/img_180_30_40.JPEG width="1000" height="150"></center>

- `how=left`: contiene solo las claves de la tabla izquierda y sobre ella completa columnas con la tabla derecha:

  <center><img src=https://raw.githubusercontent.com/ia4legos/Statistics/main/images/img_180_30_20.JPEG width="1000" height="150"></center>

- `how=right`: contiene solo las claves de la tabla derecha y con ellas completa columnas con la tabla izquierda:

  <center><img src=https://raw.githubusercontent.com/ia4legos/Statistics/main/images/img_180_30_30.JPEG width="1000" height="150"></center>



Ponemos ahora a prueba todos estos tipos de combinación sobre nuestro ejemplo, utilizando como tabla izquierda `df_caracteristicas` y como tabla derecha `df_sexo`.

In [ ]:
# combinado de dataframes con 'how=outer'
df_outer = df_caracteristicas.merge(df_sexo, on='Nombre superhéroe', how='outer', indicator = True)
df_outer.sort_values(by=['_merge'], ascending=False, ignore_index=True).style.apply(highlight11, axis=1)

Como comprobación, la longitud esperada del _dataframe_ fusionado debe ser mayor o igual que la longitud del más largo (*df_caracteristicas* en este caso). El _dataframe_ resultante tiene un total de 11 filas: 5 de ambas, 3 de la derecha y 4 de la izquierda, como se indica en la columna *_merge*, diferenciados por tres colores diferentes. Las filas en las que existe información en ambos dataframes no tienen valores faltantes, a diferencia de las que solo están en una de ellas, que se quedan con valores `nan` cuando no existía el registro de la variable en el dataframe alternativo al de procedencia.

Así, tenemos superhéroes de los que conocemos sus características pero no su sexo, y viceversa.

Probamos ahora a igualar el argumento `how='inner'`. Aparecerán los datos de los superhéroes que están compartidos en los dos dataframes (en color violeta en la tabla anterior); su dimensión será menor o igual que la dimensión del dataframe más pequeño (en este caso obtenemos 5 filas y *df_sexo*, que es el más pequeño, tiene 8).

In [ ]:
# combinado de dataframes con 'how=inner'
df_inner = df_caracteristicas.merge(df_sexo, on='Nombre superhéroe', how='inner', indicator = True)
df_inner.sort_values(by=['_merge'], ascending=False, ignore_index=True).style.apply(highlight11, axis=1)

A continuación, vamos a utilizar el método `'left'` para unir bases de datos. En este caso nos aparecerán solo los superhéroes que hay en *df_caracteristicas*, y se completará su sexo si existe el registro en *df_sexo* y aparecerá como `nan` si no existe. Quedan pues las bases de datos violeta y magenta. Su dimensión será igual a la dimensión del dataframe de la izquierda (*df_caracteristicas* en nuestro ejemplo).

In [ ]:
# combinado de dataframes con 'how=left'
df_left = df_caracteristicas.merge(df_sexo, on='Nombre superhéroe', how='left', indicator = True)
df_left.sort_values(by=['_merge'], ascending=False, ignore_index=True).style.apply(highlight11, axis=1)

Por último, cuando combinamos por la tabla de la "derecha", con `how='right'`, obtenemos un dataframe con los registros de la tabla derecha (*df_sexo*) y dimensión similar a ella, que completa la información sobre `sexo` con las columnas de *df_caracteristicas* siempre que exista valor, y con `nan` si no existe.

In [ ]:
# combinado de dataframes con 'how=right'
df_right = df_caracteristicas.merge(df_sexo, on='Nombre superhéroe', how='right', indicator = True)
df_right.sort_values(by=['_merge'], ascending=False, ignore_index=True).style.apply(highlight11, axis=1)

También podemos reproducir esta selección en Python, con los operadores de selección y los resultados del combinado con `outer`. Una vez hacemos la selección, permanecen los índices originarios, por lo que es preciso resetearlos, con la función `reset_index()`, que crea índices nuevos inicializados a cero y consecutivos, pero convierte en variable llamada `index` los índices antiguos. El paso siguiente es pues, eliminar dicha columna.

In [ ]:
# Selección de registros que solo están en uno de los dos dataframes combinados
df_inner_comp = df_outer[df_outer["_merge"]!="both"].reset_index().drop(["index"], axis=1)
df_inner_comp.style.apply(highlight11, axis=1)

In [ ]:
# Selección de registros que solo están el dataframe izquierdo (excluyendo compartidos con el otro)
df_no_left = df_left[df_left["_merge"]=="left_only"].reset_index().drop(["index"], axis=1)
df_no_left.style.apply(highlight11, axis=1)

In [ ]:
# Selección de registros que solo están el dataframe derecho (excluyendo compartidos con el otro)
df_no_right = df_right[df_right["_merge"]=="right_only"].reset_index().drop(["index"], axis=1)
df_no_right.style.apply(highlight11, axis=1)

Otra función que nos ayuda a unir bases de datos anexando columnas en dataframes distintos es **`join()`**, también en el módulo _Pandas_. El resultado que produce es el equivalente a la función `merge(...,how='left')`. Esta función se aplica al dataframe izquierdo, y permite anexar y combinar la información existente en el derecho, que pasamos como argumento, especificando en él como índice la columna clave, con `set_index("col_clave")`, y la columna clave en el dataframe inicial con el argumento `on`.

Siguiendo la nomenclatura que hemos venido utilizando para mostrar de modo genérico la sintaxis, la regla de uso de `join()` viene dada por:
```
df_izquierdo.join(df_derecho.set_index("Clave_derecho"),
                   on="Clave_izquierdo")
```

In [ ]:
# Combinación de dataframes con 'join'.
df_join = df_caracteristicas.join(df_sexo.set_index('Nombre superhéroe'), on='Nombre superhéroe')
df_join.style.apply(highlight12, axis=1)

La función `join()` no nos da información sobre la proveniencia de cada uno de los registros en el combinado final, como sí hacía `merge()`. El criterio de unión que utiliza es el de los índices. Si previamente a utilizarla modificamos los índices en los dos dataframes para que se correspondan con la columna clave, no será necesario utilizar el argumento `on` y obtendremos un combinado en el que la columna clave o relacional quedará como índice, y no como variable; si quisiéramos recuperarla como columna, bastaría resetear el índice con `reset_index()`, como ya vimos antes.

In [ ]:
# Especificación de índices antes del combinado con join
df_join2 = df_caracteristicas.set_index('Nombre superhéroe').join(df_sexo.set_index('Nombre superhéroe'))
df_join2.style.apply(highlight12, axis=1)

<pandas.io.formats.style.Styler object at 0x7985db953eb0>
<pandas.io.formats.style.Styler object at 0x7985db952680>

In [ ]:
# Recuperación de la columna clave
df_join2.reset_index().style.apply(highlight12, axis=1)